FROM registry.access.redhat.com/ubi8/nodejs-16

ENV PORT 9000
ARG WEBSITE_HOSTNAME

ARG SLACK_COC
ARG SLACK_CHANNELS
ARG SLACK_SUBDOMAIN
ARG SLACK_API_TOKEN
ARG EMAIL_SLACK_LIST
ENV SLACK_INTERVAL 5000

ARG GOOGLE_CAPTCHA_SECRET
ARG GOOGLE_CAPTCHA_SITEKEY

ADD . /slackin

WORKDIR /slackin

RUN npm i

EXPOSE $PORT

ENTRYPOINT ["npm", "run", "start"]
